invalid-item: '&6&lPrimeItems &8&l| &cУ вас в руке воздух!'
not-player: '&cИспользуйте команду от имени игрока!'
no-permission: '&6&lPrimeItems &8&l| &cУ вас не достаточно прав!'
succes-set-name: '&6&lPrimeItems &8&l| &7Вы успешно добавили имя предмету &r%name%'
succes-add-lore: '&6&lPrimeItems &8&l| &7Вы успешно добавили лор предмету &r%lore%'
succes-del-lore: '&6&lPrimeItems &8&l| &7Вы успешно убрали строку &a%number% &7лора у предмета'
no-lore: '&6&lPrimeItems &8&l| &cУ предмета нет лора!'
not-int: '&6&lPrimeItems &8&l| &cВведёное вами число не является целым числом!'
lore-size: '&6&lPrimeItems &8&l| &cВведёное вами число больше чем количество строк лора!'
item-info:
  - '&6&lPrimeItems &8&l| &7Информация'
  - '&7Имя: &f%name%'
  - '&7Материал: &f%material%'
  - '&7Количество: &f%amount%'
  - '&7Описание: '
help:
  - '&6&lPrimeItems &8&l| &7Помощь'
  - '&7/primeitems info - &fИнформация о предмете'
  - '&7/primeitems setname [имя] - &fУстановить имя предмету'
  - '&7/primeitems addlore [строка] - &fДобавить строку к лору предмета'
  - '&7/primeitems dellore [номер] - &fДобавить строку к лору предмета'